osx_image: xcode8.2
language: objective-c
script: xcodebuild test -scheme 'TTToolbox iOS' -destination 'platform=iOS Simulator,name=iPad Pro (12.9 inch),OS=10.2' && xcodebuild test -scheme 'TTToolbox MacOS' -destination "platform=OS X"
notifications:
  email: false
